logos = {
    "Atlanta United FC": "ATL.svg",
    "Austin FC": "ATX.svg",
    "Chicago Fire FC": "CHI.svg",
    "FC Cincinnati": "CIN.svg",
    "Columbus Crew SC": "CLB.svg",
    "Charlotte FC": "CLT.svg",
    "Colorado Rapids": "COL.svg",
    "FC Dallas": "DAL.svg",
    "D.C. United": "DC.svg",
    "Houston Dynamo FC": "HOU.svg",
    "LA Galaxy": "LA.svg",
    "Los Angeles FC": "LAFC.svg",
    "Inter Miami CF": "MIA.svg",
    "Minnesota United FC": "MIN.svg",
    "Club de Foot Montréal": "MontrealClub.svg",
    "New England Revolution": "NE.svg",
    "Nashville SC": "NSH.svg",
    "New York City FC": "NYC.svg",
    "Orlando City SC": "ORL.svg",
    "Philadelphia Union": "PHI.svg",
    "Portland Timbers": "POR.svg",
    "New York Red Bulls": "RBNY.svg",
    "Real Salt Lake": "RSL.svg",
    "Seattle Sounders FC": "SEA.png",
    "San Jose Earthquakes": "SJ.svg",
    "Sporting Kansas City": "SKC.svg",
    "St. Louis City SC": "STL.svg",
    "San Diego": "SanDiego.png",
    "Toronto FC": "TOR.svg",
    "Vancouver Whitecaps FC": "VAN.svg",
};